version: '3.7'

services:
  web: 
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/opt/redis_data
    ports:
      - "80:8888"
    environment:
      CONTAINER_TYPE: web

redis:
  image: redis:5.0.6-alpine
  ports:
    - target: 6379
      published: 6379
  expose:
    - 6379
